### ISSUE TITLE
How to send request to create or update a group of contacts

### ISSUE THREAD

**Issue by ssharma0312** [squaredup/HubSpot.NET#25]
HubSpot api has endpoint as specified here: https://developers.hubspot.com/docs/methods/contacts/batch_create_or_update
to create multiple contacts in one request

**Comment by bfutrell70** [comment]
It's in there under HubSpot.NET.Api.Contact.

In order to call it you would need to build a list of contacts to add/update and then call it like this:

var api = new HubSpotApi([Your API Key here]);
api.Contact.Batch([Your list of contacts to add or update]);

There are a couple of drawbacks to batch creating/updating contacts:

- no results are returned - if you need to access fields from a newly added contact you won't be able to do it using the Batch method.
- if there is a single error in the list of contacts none of them will be processed
